/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import GUI.*;
import BUS.LoginBUS;
import BUS.QLNVBUS;
import DTO.LoginDTO;
import DTO.QLNVDTO;
import java.awt.event.KeyEvent;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import GUI.frame;
/**
 *
 * @author 
 */
public class Login1 extends javax.swing.JFrame {

    static int typehienhanh;

    String UserText, PassText;
//    public static String idhienhanh;
    
    public static int type = 0;

    public ArrayList<LoginDTO> Arr_Thongtin = new ArrayList<>();

    /**
     * Creates new form Login
     */

    public Login1() {
        initComponents();
        
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
     
        setLocationRelativeTo(null);
        setVisible(true);
       
    }
    public static LoginDTO login = null;
    public static Statement st = null;
    public static ResultSet rs = null;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jUserField1 = new javax.swing.JTextField();
        jPasswordField1 = new javax.swing.JPasswordField();
        jCheckBox1 = new javax.swing.JCheckBox();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jSubmitLabel = new javax.swing.JLabel();
        jLoginPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jSignUpPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLoginPanel2 = new javax.swing.JPanel();
        jLoginDK8 = new javax.swing.JLabel();
        jSignUpPanel4 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jDangKiLabel1 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        jPasswordFieldDK2 = new javax.swing.JPasswordField();
        jUserFieldDK2 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jPasswordFieldDK3 = new javax.swing.JPasswordField();
        jSeparator7 = new javax.swing.JSeparator();
        jLabel13 = new javax.swing.JLabel();
        jCheckBox2 = new javax.swing.JCheckBox();
        manvTf = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        maNvlogin = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));
        jPanel2.setFocusable(false);
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jUserField1.setBackground(new java.awt.Color(51, 51, 51));
        jUserField1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jUserField1.setForeground(new java.awt.Color(255, 255, 255));
        jUserField1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jUserField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jUserField1ActionPerformed(evt);
            }
        });
        jPanel2.add(jUserField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 210, 250, 30));

        jPasswordField1.setBackground(new java.awt.Color(51, 51, 51));
        jPasswordField1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jPasswordField1.setForeground(new java.awt.Color(255, 255, 255));
        jPasswordField1.setBorder(null);
        jPasswordField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordField1ActionPerformed(evt);
            }
        });
        jPasswordField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jPasswordField1KeyPressed(evt);
            }
        });
        jPanel2.add(jPasswordField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 280, 250, 30));

        jCheckBox1.setForeground(new java.awt.Color(255, 255, 255));
        jCheckBox1.setText("Hiện mật khẩu");
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });
        jPanel2.add(jCheckBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 330, 101, -1));

        jSeparator1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 310, 250, 20));

        jSeparator2.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 240, 250, 20));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/user (2).png"))); // NOI18N
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 210, 73, 30));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/padlock.png"))); // NOI18N
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 280, 50, 30));

        jSubmitLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jSubmitLabel.setForeground(new java.awt.Color(255, 255, 255));
        jSubmitLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jSubmitLabel.setText("ĐĂNG NHẬP");
        jSubmitLabel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 204, 255), 2));
        jSubmitLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jSubmitLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jSubmitLabelMouseClicked(evt);
            }
        });
        jPanel2.add(jSubmitLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 380, 260, 50));

        jLoginPanel1.setBackground(new java.awt.Color(0, 204, 255));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Login");
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout jLoginPanel1Layout = new javax.swing.GroupLayout(jLoginPanel1);
        jLoginPanel1.setLayout(jLoginPanel1Layout);
        jLoginPanel1Layout.setHorizontalGroup(
            jLoginPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
        );
        jLoginPanel1Layout.setVerticalGroup(
            jLoginPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        jPanel2.add(jLoginPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, 190, 40));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Sign Up");
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jSignUpPanel3Layout = new javax.swing.GroupLayout(jSignUpPanel3);
        jSignUpPanel3.setLayout(jSignUpPanel3Layout);
        jSignUpPanel3Layout.setHorizontalGroup(
            jSignUpPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
        );
        jSignUpPanel3Layout.setVerticalGroup(
            jSignUpPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        jPanel2.add(jSignUpPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 40, 190, 40));
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 100, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 153, 204));
        jLabel6.setText("USER LOGIN");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 150, -1, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 450, 520));

        jPanel3.setBackground(new java.awt.Color(51, 51, 51));
        jPanel3.setFocusable(false);
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLoginPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLoginPanel2MouseClicked(evt);
            }
        });

        jLoginDK8.setBackground(new java.awt.Color(51, 51, 51));
        jLoginDK8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLoginDK8.setForeground(new java.awt.Color(51, 51, 51));
        jLoginDK8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLoginDK8.setText("Login");
        jLoginDK8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLoginDK8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLoginDK8MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jLoginPanel2Layout = new javax.swing.GroupLayout(jLoginPanel2);
        jLoginPanel2.setLayout(jLoginPanel2Layout);
        jLoginPanel2Layout.setHorizontalGroup(
            jLoginPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLoginDK8, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
        );
        jLoginPanel2Layout.setVerticalGroup(
            jLoginPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLoginDK8, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        jPanel3.add(jLoginPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, 190, 40));

        jSignUpPanel4.setBackground(new java.awt.Color(0, 204, 255));
        jSignUpPanel4.setForeground(new java.awt.Color(255, 255, 255));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Sign Up");
        jLabel9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout jSignUpPanel4Layout = new javax.swing.GroupLayout(jSignUpPanel4);
        jSignUpPanel4.setLayout(jSignUpPanel4Layout);
        jSignUpPanel4Layout.setHorizontalGroup(
            jSignUpPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
        );
        jSignUpPanel4Layout.setVerticalGroup(
            jSignUpPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        jPanel3.add(jSignUpPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 40, 190, 40));

        jDangKiLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jDangKiLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jDangKiLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jDangKiLabel1.setText("ĐĂNG KÍ");
        jDangKiLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 204, 255), 2));
        jDangKiLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jDangKiLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jDangKiLabel1MouseClicked(evt);
            }
        });
        jPanel3.add(jDangKiLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 450, 260, 50));

        jSeparator3.setForeground(new java.awt.Color(255, 255, 255));
        jPanel3.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 270, 250, 20));

        jSeparator6.setForeground(new java.awt.Color(255, 255, 255));
        jPanel3.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 340, 250, 20));

        jPasswordFieldDK2.setBackground(new java.awt.Color(51, 51, 51));
        jPasswordFieldDK2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jPasswordFieldDK2.setForeground(new java.awt.Color(255, 255, 255));
        jPasswordFieldDK2.setBorder(null);
        jPasswordFieldDK2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordFieldDK2ActionPerformed(evt);
            }
        });
        jPasswordFieldDK2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jPasswordFieldDK2KeyPressed(evt);
            }
        });
        jPanel3.add(jPasswordFieldDK2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 310, 250, 30));

        jUserFieldDK2.setBackground(new java.awt.Color(51, 51, 51));
        jUserFieldDK2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jUserFieldDK2.setForeground(new java.awt.Color(255, 255, 255));
        jUserFieldDK2.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jUserFieldDK2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jUserFieldDK2ActionPerformed(evt);
            }
        });
        jPanel3.add(jUserFieldDK2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 240, 250, 30));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/user (2).png"))); // NOI18N
        jPanel3.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 240, -1, -1));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/padlock.png"))); // NOI18N
        jPanel3.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 370, -1, -1));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Sign Up For Free");
        jPanel3.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 120, -1, -1));

        jPasswordFieldDK3.setBackground(new java.awt.Color(51, 51, 51));
        jPasswordFieldDK3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jPasswordFieldDK3.setForeground(new java.awt.Color(255, 255, 255));
        jPasswordFieldDK3.setBorder(null);
        jPasswordFieldDK3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordFieldDK3ActionPerformed(evt);
            }
        });
        jPasswordFieldDK3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jPasswordFieldDK3KeyPressed(evt);
            }
        });
        jPanel3.add(jPasswordFieldDK3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 370, 250, 30));

        jSeparator7.setForeground(new java.awt.Color(255, 255, 255));
        jPanel3.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 400, 250, 20));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/padlock.png"))); // NOI18N
        jPanel3.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 310, -1, -1));

        jCheckBox2.setForeground(new java.awt.Color(255, 255, 255));
        jCheckBox2.setText("Hiện mật khẩu");
        jCheckBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox2ActionPerformed(evt);
            }
        });
        jPanel3.add(jCheckBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 410, 140, 20));

        manvTf.setBackground(new java.awt.Color(51, 51, 51));
        manvTf.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        manvTf.setForeground(new java.awt.Color(255, 255, 255));
        manvTf.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        manvTf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manvTfActionPerformed(evt);
            }
        });
        jPanel3.add(manvTf, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 180, 100, 30));

        jSeparator4.setForeground(new java.awt.Color(255, 255, 255));
        jPanel3.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 210, 100, 20));

        maNvlogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/staff_32px.png"))); // NOI18N
        jPanel3.add(maNvlogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 190, -1, -1));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 450, 520));
        jPanel3.setVisible(false);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        if (jCheckBox1.isSelected()) {
            jPasswordField1.setEchoChar((char) 0);
        } else {
            jPasswordField1.setEchoChar('*');
        }
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    private void jPasswordField1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPasswordField1KeyPressed
        if (evt.getKeyCode()==KeyEvent.VK_ENTER){
            LoginBUS bus = new LoginBUS();
            int i = 0;
            if (LoginBUS.Arr_login.size() == 0) {
                try {
                    bus.docdangnhap();
                } catch (Exception e) {
                }
            }
            if (this.jUserField1.getText().equals("") || String.valueOf(this.jPasswordField1.getPassword()).equals("")) {
                JOptionPane.showMessageDialog(this, "Bạn chưa nhập thông tin tài khoản hoặc mật khẩu", "Thông báo", 1);
            } else {
                try {
                    for (LoginDTO login1 : LoginBUS.Arr_login) {
                        UserText = jUserField1.getText();
                        PassText = String.valueOf(jPasswordField1.getPassword());
                        if (UserText.equals(login1.username) && PassText.equals(login1.password)) 
                        {                                                
                            if (login1.getType() == 2){
                                JOptionPane.showMessageDialog(null, "Bạn đã đăng nhập bằng tài khoản admin", "Thông báo", 1);
                                typehienhanh = login1.getType();
                                dispose();
                                new frame(String.valueOf(login1.getId())).setVisible(true);
                                break;
                            } else {
                                  JOptionPane.showMessageDialog(null, "Bạn đã đăng nhập bằng tài khoản nhân viên, HI "+UserText, "Thông báo", 1);
                                  typehienhanh = login1.getType();
                                  dispose();
                                  new frame(String.valueOf(login1.getId())).setVisible(true);
                                break;                                                
                                 }
                        }
                         else {
                            i++;
                            if (i == LoginBUS.Arr_login.size()) {
                                JOptionPane.showMessageDialog(null, "Tài khoản hoặc mật khẩu không chính xác, vui lòng nhập lại!", "Thông báo", 1);
                            }

                            }
                } 

            }
                catch (Exception ex) {
                }
        }
    }//GEN-LAST:event_jPasswordField1KeyPressed
}
    private void jPasswordField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordField1ActionPerformed

    private void jUserField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jUserField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jUserField1ActionPerformed

    private void jSubmitLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jSubmitLabelMouseClicked
        // TODO add your handling code here:
        LoginBUS bus = new LoginBUS();
            int i = 0;
            if (LoginBUS.Arr_login.size() == 0) {
                try {
                    bus.docdangnhap();
                } catch (Exception e) {
                }
            }
            if (this.jUserField1.getText().equals("") || String.valueOf(this.jPasswordField1.getPassword()).equals("")) {
                JOptionPane.showMessageDialog(this, "Bạn chưa nhập thông tin tài khoản hoặc mật khẩu", "Thông báo", 1);
            } else {
                try {
                    for (LoginDTO login1 : LoginBUS.Arr_login) {
                        UserText = jUserField1.getText();
                        PassText = String.valueOf(jPasswordField1.getPassword());
                        if (UserText.equals(login1.username) && PassText.equals(login1.password)) 
                        {                                                
                            if (login1.getType() == 2){
                                JOptionPane.showMessageDialog(null, "Bạn đã đăng nhập bằng tài khoản admin", "Thông báo", 1);
                                typehienhanh = login1.getType();
                                dispose();
                                new frame(String.valueOf(login1.getId())).setVisible(true);
                                break;
                            } else {
                                  JOptionPane.showMessageDialog(null, "Bạn đã đăng nhập bằng tài khoản nhân viên, HI "+UserText, "Thông báo", 1);
                                  typehienhanh = login1.getType();
                                  dispose();
                                  frame a=new frame(String.valueOf(login1.getId()));    
                                  a.setVisible(true);
                                  this.dispose();
                                break;                                                
                                 }
                        }
                         else {
                            i++;
                            if (i == LoginBUS.Arr_login.size()) {
                                JOptionPane.showMessageDialog(null, "Tài khoản hoặc mật khẩu không chính xác, vui lòng nhập lại!", "Thông báo", 1);
                            }

                            }
                    }
                }       catch (Exception ex) {
                    }

            }
    }//GEN-LAST:event_jSubmitLabelMouseClicked

    private void jDangKiLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jDangKiLabel1MouseClicked
        // TODO add your handling code here:
        try{
            QLNVBUS b = new QLNVBUS();
            b.docDSNV();
            LoginDTO lg = new LoginDTO();
            LoginBUS bus = new LoginBUS();
            bus.docdangnhap();
            lg.username=jUserFieldDK2.getText();
            lg.password=String.valueOf(jPasswordFieldDK2.getPassword());
            lg.type=1;
            lg.setId(Integer.parseInt(manvTf.getText()));
            if(b.getNv(String.valueOf(lg.getId()))==null){
                JOptionPane.showMessageDialog(null, "Mã nhân viên không tồn tại");
                manvTf.setText(null);
            }
            else{
                if (bus.checkusername(lg.getUsername())){
                JOptionPane.showMessageDialog(null, "Username đã được đăng kí");
                jUserField1.setText(null);
                }
                else{          
                    if(bus.checkid(lg.getId())){
                        JOptionPane.showMessageDialog(null, "Mã nhân viên đã được đăng kí");
                        manvTf.setText(null);
                    }
                    else{                      
                            if(String.valueOf(jPasswordFieldDK2.getPassword()).equals(String.valueOf(jPasswordFieldDK3.getPassword())))
                            {
                            JOptionPane.showMessageDialog(null, "Đăng kí tài khoản thành công");
                            manvTf.setText(null);
                            jUserFieldDK2.setText(null);
                            jPasswordFieldDK2.setText(null);
                            jPasswordFieldDK3.setText(null);
                            bus.ThemTaiKhoan(lg);
                            jPanel2.setVisible(true);
                            //dispose();
                            jPanel3.setVisible(false);
                            manvTf.setText(null);
                            jUserFieldDK2.setText(null);
                            jPasswordFieldDK2.setText(null);
                            jPasswordFieldDK3.setText(null);
                            }   
                        else{
                            JOptionPane.showMessageDialog(null,"Nhập lại mật khẩu chưa chính xác");
                            jPasswordFieldDK3.setText(null);
                            }
                        }
                    }      
                }
            
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,"Đăng kí không thành công");
            manvTf.setText(null);
            jUserFieldDK2.setText(null);
            jPasswordFieldDK2.setText(null);
            jPasswordFieldDK3.setText(null);
        }
    }//GEN-LAST:event_jDangKiLabel1MouseClicked

    private void jPasswordFieldDK2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordFieldDK2ActionPerformed
        // TODO add your handling code here: 
    }//GEN-LAST:event_jPasswordFieldDK2ActionPerformed

    private void jPasswordFieldDK2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPasswordFieldDK2KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordFieldDK2KeyPressed

    private void jUserFieldDK2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jUserFieldDK2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jUserFieldDK2ActionPerformed

    private void jPasswordFieldDK3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordFieldDK3ActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jPasswordFieldDK3ActionPerformed

    private void jPasswordFieldDK3KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPasswordFieldDK3KeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
           try{
            QLNVBUS b = new QLNVBUS();
            b.docDSNV();
            LoginDTO lg = new LoginDTO();
            LoginBUS bus = new LoginBUS();
            bus.docdangnhap();
            lg.username=jUserFieldDK2.getText();
            
            lg.password=String.valueOf(jPasswordFieldDK2.getPassword());
            lg.type=1;
            lg.setId(Integer.parseInt(manvTf.getText()));
            if(b.getNv(String.valueOf(lg.getId()))==null){
                JOptionPane.showMessageDialog(null, "Mã nhân viên không tồn tại");
                manvTf.setText(null);
                
            }
          
            else{
                if (bus.checkusername(lg.getUsername())){
                JOptionPane.showMessageDialog(null, "Username đã được đăng kí");
                jUserField1.setText(null);
                }
                else{          
                    if(bus.checkid(lg.getId())){
                        JOptionPane.showMessageDialog(null, "Mã nhân viên đã được đăng kí");
                        manvTf.setText(null);
                    }
                    else{                      
                            if(String.valueOf(jPasswordFieldDK2.getPassword()).equals(String.valueOf(jPasswordFieldDK3.getPassword())))
                            {
                            JOptionPane.showMessageDialog(null, "Đăng kí tài khoản thành công");
                            manvTf.setText(null);
                            jUserFieldDK2.setText(null);
                            jPasswordFieldDK2.setText(null);
                            jPasswordFieldDK3.setText(null);
                            bus.ThemTaiKhoan(lg);
                            jPanel2.setVisible(true);
                            //dispose();
                            jPanel3.setVisible(false);
                            manvTf.setText(null);
                            jUserFieldDK2.setText(null);
                            jPasswordFieldDK2.setText(null);
                            jPasswordFieldDK3.setText(null);
                            }   
                        else{
                            JOptionPane.showMessageDialog(null,"Nhập lại mật khẩu chưa chính xác");
                            jPasswordFieldDK3.setText(null);
                            }
                        }
                    }      
                }
            
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,"Đăng kí không thành công");
            manvTf.setText(null);
            jUserFieldDK2.setText(null);
            jPasswordFieldDK2.setText(null);
            jPasswordFieldDK3.setText(null);
        }
     }                               
        
    }//GEN-LAST:event_jPasswordFieldDK3KeyPressed

    private void jCheckBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox2ActionPerformed
        // TODO add your handling code here:
        if (jCheckBox2.isSelected()) {
            jPasswordFieldDK2.setEchoChar((char) 0);
        } else {
            jPasswordFieldDK2.setEchoChar('*');
        }
        if (jCheckBox2.isSelected()) {
            jPasswordFieldDK3.setEchoChar((char) 0);
        } else {
            jPasswordFieldDK3.setEchoChar('*');
        }
                       
    }//GEN-LAST:event_jCheckBox2ActionPerformed

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        // TODO add your handling code here:
        jPanel3.setVisible(true);
        jPanel2.setVisible(false);
    }//GEN-LAST:event_jLabel1MouseClicked

    private void jLoginDK8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLoginDK8MouseClicked
        // TODO add your handling code here:
        jPanel2.setVisible(true);
        jPanel3.setVisible(false);
    }//GEN-LAST:event_jLoginDK8MouseClicked

    private void jLoginPanel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLoginPanel2MouseClicked
        // TODO add your handling code here:
        jPanel2.setVisible(true);
        jPanel3.setVisible(false);
    }//GEN-LAST:event_jLoginPanel2MouseClicked

    private void manvTfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manvTfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_manvTfActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JLabel jDangKiLabel1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLoginDK8;
    private javax.swing.JPanel jLoginPanel1;
    private javax.swing.JPanel jLoginPanel2;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JPasswordField jPasswordFieldDK2;
    private javax.swing.JPasswordField jPasswordFieldDK3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JPanel jSignUpPanel3;
    private javax.swing.JPanel jSignUpPanel4;
    private javax.swing.JLabel jSubmitLabel;
    private javax.swing.JTextField jUserField1;
    private javax.swing.JTextField jUserFieldDK2;
    private javax.swing.JLabel maNvlogin;
    private javax.swing.JTextField manvTf;
    // End of variables declaration//GEN-END:variables
}
